//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("GitTfs")]
[assembly: AssemblyProduct("GitTfs")]
[assembly: AssemblyVersion("0.30.9")]
[assembly: AssemblyFileVersion("0.30.9")]
[assembly: AssemblyInformationalVersion("0.30.9+5860b68c16f3d44c968176758bd23137ea5d9adf.master")]
[assembly: AssemblyCopyright("Copyright © 2009-2019")]

